window.curatedProfiles = [
  {
    id: "angelica",
    name: "Angelica",
    age: 31,
    city: "Milano",
    bio: "E una persona che prende tempo prima di esporsi davvero. Non per distanza, ma per capire il contesto, le sfumature, le intenzioni. Si sente a suo agio nelle conversazioni che non hanno fretta di arrivare a una conclusione e nelle stanze in cui non serve alzare la voce per essere ascoltati.",
    highlights: [
      "Quando il gruppo si disperde o l'energia cala, e quella che rimane lucida e affidabile, anche se non lo rivendica mai.",
      "Sta imparando a dire cosa pensa nel momento in cui lo pensa, senza aspettare che passi.",
    ],
    lookingFor: ["Amicizia con 🍆, 🍑", "Relazione seria con 🍆"],
    question:
      "Qual e una situazione in cui ti sei accorto di adattarti troppo, e cosa hai fatto dopo?",
    photos: [
      "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=900&q=80",
    ],
  },
  {
    id: "tommaso",
    name: "Tommaso",
    age: 34,
    city: "Bologna",
    bio: "Lavora nel suono, ma preferisce le persone che parlano piano. E diretto senza essere invadente, e non confonde l'intensita con la fretta. Ha bisogno di relazioni in cui ci si sente liberi di cambiare idea senza perdere fiducia.",
    highlights: [
      "Quando c'e caos, rimette ordine con calma e ironia.",
      "Se una conversazione e vera, la porta avanti con presenza costante.",
    ],
    lookingFor: ["Relazione seria con 🍑", "Connessioni autentiche con 🍑, 🍆"],
    question: "Cosa fai quando ti accorgi che stai performando invece di esserci?",
    photos: [
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
    ],
  },
  {
    id: "giulia",
    name: "Giulia",
    age: 29,
    city: "Torino",
    bio: "Ama le cose ben fatte e le persone non ambigue. E presente, attenta, molto autoironica. Non cerca qualcuno da incastrare in una routine, ma qualcuno con cui far evolvere una quotidianita che abbia senso per entrambi.",
    highlights: [
      "Ha una gentilezza concreta: si nota nei dettagli, non nelle dichiarazioni.",
      "Quando sbaglia, torna sulla questione invece di far finta di niente.",
    ],
    lookingFor: ["Relazione seria con 🍆", "Amicizia con 🍑"],
    question: "Quale conflitto hai imparato a gestire meglio negli ultimi anni?",
    photos: [
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?auto=format&fit=crop&w=900&q=80",
    ],
  },
  {
    id: "luca",
    name: "Luca",
    age: 36,
    city: "Roma",
    bio: "E una persona affidabile, ma non rigida. Ha imparato a chiedere spazio prima di saturarsi e ad ascoltare senza offrire subito una soluzione. Preferisce i legami che crescono in modo organico, senza sceneggiature.",
    highlights: [
      "Tiene insieme il gruppo con discrezione, senza mettersi al centro.",
      "Non fugge quando arrivano conversazioni scomode.",
    ],
    lookingFor: ["Relazione seria con 🍑", "Amicizia con 🍆"],
    question: "Quando ti senti veramente visto da qualcuno?",
    photos: [
      "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1542204625-de293a6b4178?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80",
    ],
  },
  {
    id: "marta",
    name: "Marta",
    age: 32,
    city: "Firenze",
    bio: "Alterna periodi sociali a momenti di ritiro, senza viverlo come un difetto. Le piace quando una relazione lascia spazio al silenzio, ai tempi personali, alla possibilita di esserci senza performare.",
    highlights: [
      "Riconosce presto quando una situazione non e sana e lo dice con rispetto.",
      "Non confonde compatibilita con somiglianza totale.",
    ],
    lookingFor: ["Connessioni autentiche con 🍆, 🍑", "Relazione seria con 🍆"],
    question: "Che tipo di attenzione ti fa sentire a casa?",
    photos: [
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?auto=format&fit=crop&w=900&q=80",
    ],
  },
  {
    id: "davide",
    name: "Davide",
    age: 30,
    city: "Napoli",
    bio: "Ha energia e leggerezza, ma e molto serio nel modo in cui tratta gli altri. E attratto dalle persone che sanno essere ironiche e vulnerabili insieme. Cerca un ritmo condiviso, non una prova da superare.",
    highlights: [
      "Nei gruppi aiuta chi resta ai margini a rientrare nella conversazione.",
      "E capace di cambiare idea quando capisce di aver ascoltato poco.",
    ],
    lookingFor: ["Relazione seria con 🍑", "Amicizia con 🍆, 🍑"],
    question: "Quale confine personale hai imparato a proteggere meglio?",
    photos: [
      "https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?auto=format&fit=crop&w=900&q=80",
    ],
  },
];
